name: Deploy to production
on:
  push:
    branches:
      - 'production'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy deploy-prod.sh file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.STAGING_PORT }}
          username: ${{ secrets.STAGING_USERNAME }}
          source: ".scripts/deploy-prod.sh"
          target: /var/www/rent-ratings/
          key: ${{ secrets.STAGING_SSHKEY }}
          overwrite: true
      - name: Run deploy.sh file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          port: ${{ secrets.STAGING_PORT }}
          key: ${{ secrets.STAGING_SSHKEY }}
          script: "cd /var/www/rent-ratings && chmod +x .scripts/deploy-prod.sh && ./.scripts/deploy-prod.sh"
