name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy deploy.sh file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .scripts/deploy.sh
          remote: /var/www/html/.scripts/deploy.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          privateKey: ${{ secrets.SSHKEY }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/html && chmod +x .scripts/deploy.sh && ./.scripts/deploy.sh"
