name: Deploy to staging
on:
  push:
    branches:
      - 'deploy'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy deploy.sh file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          port: ${{ secrets.STAGING_PORT }}
          username: ${{ secrets.STAGING_USERNAME }}
          source: ".scripts/deploy.sh"
          target: /var/www/rent-ratings/.scripts/deploy.sh
          key: ${{ secrets.STAGING_SSHKEY }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          port: ${{ secrets.STAGING_PORT }}
          key: ${{ secrets.STAGING_SSHKEY }}
          script: "cd /var/www/rent-ratings && chmod +x .scripts/deploy.sh && ./.scripts/deploy.sh"
