name: Deploy to staging
on:
  push:
    branches:
      - 'develop'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy deploy.sh file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .scripts/deploy.sh
          remote: /var/www/html/.scripts/deploy.sh
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          port: ${{ secrets.STAGING_PORT }}
          privateKey: ${{ secrets.STAGING_SSHKEY }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          port: ${{ secrets.STAGING_PORT }}
          key: ${{ secrets.STAGING_SSHKEY }}
          script: "cd /var/www/rent-ratings && chmod +x .scripts/deploy.sh && ./.scripts/deploy.sh"
